Disable javadoc plugin
Issue below, and I don't think many people have use for the javadoc
anyway with the sources already available.

```
1 error
17 warnings
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.614 s
[INFO] Finished at: 2017-09-02T01:19:44+02:00
[INFO] Final Memory: 33M/322M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.0-M1:jar (attach-javadocs) on project asm6: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - /home/tiste/dev/JENKINS/JIGSAW/package-renamed-asm/target/generated-sources/shaded/org/kohsuke/asm6/optimizer/ModuleInfoBndPlugin.java:11: error: package aQute.bnd.header does not exist
[ERROR] import aQute.bnd.header.Attrs;
[ERROR] ^
[ERROR] /home/tiste/dev/JENKINS/JIGSAW/package-renamed-asm/target/generated-sources/shaded/org/kohsuke/asm6/optimizer/ModuleInfoBndPlugin.java:12: error: package aQute.bnd.header does not exist
[ERROR] import aQute.bnd.header.Parameters;
[ERROR] ^
[ERROR] /home/tiste/dev/JENKINS/JIGSAW/package-renamed-asm/target/generated-sources/shaded/org/kohsuke/asm6/optimizer/ModuleInfoBndPlugin.java:13: error: package aQute.bnd.osgi does not exist
[ERROR] import aQute.bnd.osgi.Analyzer;
[ERROR] ^
[ERROR] /home/tiste/dev/JENKINS/JIGSAW/package-renamed-asm/target/generated-sources/shaded/org/kohsuke/asm6/optimizer/ModuleInfoBndPlugin.java:14: error: package aQute.bnd.osgi does not exist
[ERROR] import aQute.bnd.osgi.Constants;
[ERROR] ^
[ERROR] /home/tiste/dev/JENKINS/JIGSAW/package-renamed-asm/target/generated-sources/shaded/org/kohsuke/asm6/optimizer/ModuleInfoBndPlugin.java:15: error: package aQute.bnd.osgi does not exist
[ERROR] import aQute.bnd.osgi.EmbeddedResource;
[ERROR] ^
[ERROR] /home/tiste/dev/JENKINS/JIGSAW/package-renamed-asm/target/generated-sources/shaded/org/kohsuke/asm6/optimizer/ModuleInfoBndPlugin.java:16: error: package aQute.bnd.osgi does not exist
[ERROR] import aQute.bnd.osgi.Jar;
[ERROR] ^
[ERROR] /home/tiste/dev/JENKINS/JIGSAW/package-renamed-asm/target/generated-sources/shaded/org/kohsuke/asm6/optimizer/ModuleInfoBndPlugin.java:17: error: package aQute.bnd.service does not exist
[ERROR] import aQute.bnd.service.AnalyzerPlugin;
[ERROR] ^
[ERROR] /home/tiste/dev/JENKINS/JIGSAW/package-renamed-asm/target/generated-sources/shaded/org/kohsuke/asm6/optimizer/ModuleInfoBndPlugin.java:19: error: cannot find symbol
[ERROR] public class ModuleInfoBndPlugin implements AnalyzerPlugin {
[ERROR] ^
[ERROR] symbol: class AnalyzerPlugin
[ERROR] /home/tiste/dev/JENKINS/JIGSAW/package-renamed-asm/target/generated-sources/shaded/org/kohsuke/asm6/optimizer/ModuleInfoBndPlugin.java:27: error: cannot find symbol
[ERROR] public boolean analyzeJar(Analyzer analyzer) throws Exception {
[ERROR] ^
[ERROR] symbol:   class Analyzer
[ERROR] location: class ModuleInfoBndPlugin
[ERROR] javadoc: warning - No source files for package org.kohsuke.asm6
[ERROR] javadoc: warning - No source files for package org.kohsuke.asm6.tree
[ERROR] javadoc: warning - No source files for package org.kohsuke.asm6.tree.analysis
[ERROR] javadoc: warning - No source files for package org.kohsuke.asm6.util
[ERROR] javadoc: warning - No source files for package org.kohsuke.asm6.signature
[ERROR] javadoc: warning - No source files for package org.kohsuke.asm6.commons
[ERROR] javadoc: warning - No source files for package org.kohsuke.asm6.optimizer
[ERROR] javadoc: warning - No source files for package org.kohsuke.asm6.xml
[ERROR] javadoc: error - No public or protected classes found to document.
[ERROR]
[ERROR] Command line was: /home/tiste/.tools/JDKs/jdk1.8.0_131/jre/../bin/javadoc @options @packages
[ERROR]
[ERROR] Refer to the generated Javadoc files in '/home/tiste/dev/JENKINS/JIGSAW/package-renamed-asm/target/apidocs' dir.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```